version: '3.9'
services:
  db:
    image: postgres:15
    container_name: seller_inbox_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 
      TZ: Asia/Kathmandu
      PGTZ: Asia/Kathmandu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
